# Generated by Django 2.0.7 on 2018-09-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(verbose_name='Data de nascimento')),
                ('cellphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número do celular')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # ('interests', models.ManyToManyField(through='users.ProfileInterests', to='interest.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=1)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.interest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
