# Generated by Django 2.0.7 on 2018-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
        ('users', '0003_auto_20180916_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answered',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='interest.Interest'),
        ),
    ]
