# Generated by Django 3.1.7 on 2021-04-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180928_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpf'
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cellphone'
        ),
    ]
