# Generated by Django 3.1.7 on 2021-06-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20210523_2111'),
        ('users', '0005_auto_20210419_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('ranking_position', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Comentario')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.room')),
            ],
        ),
    ]
