# Generated by Django 3.1.7 on 2021-06-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210606_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='stars',
            field=models.IntegerField(default=0),
        )
    ]
