# Generated by Django 3.1.7 on 2021-06-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210608_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='score',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
    ]
