# Generated by Django 3.1.7 on 2021-05-23 21:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='Interesse'),
        )
    ]
