# Generated by Django 3.1.7 on 2021-09-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_auto_20210926_1558'),
        ('interest', '0002_auto_20210523_2111'),
    ]

    operations = [
    ]
