# Generated by Django 2.0.7 on 2018-09-02 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(verbose_name='Largura')),
                ('length', models.IntegerField(verbose_name='Comprimento')),
                ('picture_1', models.ImageField(upload_to='', verbose_name='Primeira foto')),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Segunda foto')),
                ('picture_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Terceira foto')),
                ('landlord', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
            },
        ),
    ]
