# Generated by Django 2.0.7 on 2018-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='Quarto legal', max_length=40, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Valor do aluguel'),
            preserve_default=False,
        ),
    ]
