# Generated by Django 2.0.7 on 2018-09-22 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=8, verbose_name='CEP')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=350, verbose_name='Bairro')),
                ('street', models.CharField(max_length=300, verbose_name='Rua/Av/Tv')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=500, null=True, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Facilidade/Cortesia')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição/Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Móvel/Eletrodoméstico')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição/Observação')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(verbose_name='Quantidade de quartos')),
                ('people', models.IntegerField(verbose_name='Quantidade de pessoas')),
                ('bathrooms', models.IntegerField(verbose_name='Quantidade de banheiros')),
                ('size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tamanho(m²)')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, verbose_name='Descrição')),
                ('size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tamanho(m²)')),
                ('price', models.FloatField(verbose_name='Valor do aluguel')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
                ('landlord', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='landlord', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.Room'),
        ),
    ]
