# Generated by Django 2.0.7 on 2018-09-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180922_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='room',
        ),
        migrations.AddField(
            model_name='amenity',
            name='house',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.CASCADE, to='house.House'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='house.Address'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='house.House'),
        ),
    ]
