# Generated by Django 2.0.7 on 2018-09-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20180922_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tamanho(m²)'),
        ),
    ]
