# Generated by Django 2.0.7 on 2018-09-22 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0004_auto_20180922_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='landlord',
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.OneToOneField(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='landlord', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
